nodes:
  node1: # 节点名称，即进程名称

    normal: # 状态服务的配置
      game: 10 # 启动10个线程的game线程，分别为game1、game2、game3……
      scene: 5
    
    global: # 有状态服务的配置
      global1: # 线程名，一个global1线程下可以启动多个服务
        # - union 
        # - team
        # - sceneGlobal
      global2: # 线程名，一个global2线程下可以启动多个服务
        # - chat
        - match # 匹配服，全局只有一个，启动在world1进程global2线程下



  node2: # 因为local：world1，所以该节点为远程节点，以后用服务发现的工具管理服务
    # 无状态服务
    normal:
      game: 10
      scene: 5

    # 有状态服务
    global:
      global1: 
        # - union
        - team
        - sceneGlobal
      global2:
        - chat
        - match

