local: world1
nodes:
  world1:
     # 无状态服务
    stateless:
      game: 10
      scene: 5

    # 有状态服务
    stateful:
      global1: 
        # - union
        # - team
        # - sceneGlobal
      global2:
        # - chat
        - match

  world2:
    # 无状态服务
    stateless:
      game: 10
      scene: 5

    # 有状态服务
    stateful:
      global1: 
        # - union
        - team
        - sceneGlobal
      global2:
        - chat
        - match

